### ISSUE TITLE
function starts_with

### ISSUE THREAD

**Issue by petr-klinger** [cybertec-postgresql/pg_timetable#104]
In last version:

Could not query pending interval tasks: pq: function starts_with(timetable.cron, unknown) does not exist

**Comment by pashagolub** [comment]
Hello Petr.

What PostgreSQL version?

**Comment by petr-klinger** [comment]
Hello Pavel.

PostgreSQL version 10.6.

Petr

**Comment by pashagolub** [comment]
Petr, would you please try this SQL before running `pg_timetable`:
```sql
CREATE OR REPLACE FUNCTION starts_with(text, text)
RETURNS bool AS 
$$
SELECT 
	CASE 
		WHEN length($2) > length($1) THEN 
			FALSE 
		ELSE 
			left($1, length($2)) = $2 
	END
$$
LANGUAGE SQL
IMMUTABLE STRICT PARALLEL SAFE
COST 5;
```

**Comment by pashagolub** [comment]
@petr-klinger Any success with this?

**Comment by petr-klinger** [comment]
Yes, after adding the function to server 10.6 without errors

**Comment by pashagolub** [comment]
Thanks a lot! Added additional info to the readme.me
