### ISSUE TITLE
pgengine parameters

### ISSUE THREAD

**Issue by petr-klinger** [cybertec-postgresql/pg_timetable#114]
Other programs can call perfect pg_timetable. Then set the interface via pgengine parameters such as pgengine.VerboseLogLevel = * boolPtrVer or pgengine.NoShellTasks = false. Then it is not necessary to extend command-line parameters, but at the same time allow for wider functionality of pg_timetable. 

I propose parameters pgengine.dateformat and pgengine.showpassword for DEBUG log

**Comment by pashagolub** [comment]
Hello.

Sorry, I'm not sure I understand you right. You mean you can use `pg_timetable` sources in other programs?
