### ISSUE TITLE
Add SQL notices to timetable.execution_log (output)

### ISSUE THREAD

**Issue by a-mckinley** [cybertec-postgresql/pg_timetable#117]
Hi,

I originally opened #69 about SQL notice processing and am now upgrading my app to use master at commit e4b1d8c7.

I can now see the notices in timetable.log, but nothing in the corresponding row in timetable.execution_log.  Could those notice lines be added to that table?

Is there a way to configure this that I am missing or is output only currently captured for shell tasks?

**Comment by pashagolub** [comment]
Hello, 

after investigations, we found there is no easy and straightforward way to assign NOTICEs with chain running. They are caught asynchronously. Thus one needs to check `timetable.log` or a server log for notices.
