### ISSUE TITLE
Optionally delete timetable.base_task for self destruct tasks?

### ISSUE THREAD

**Issue by a-mckinley** [cybertec-postgresql/pg_timetable#132]
I find it quite convenient to call timetable.job_add() with run_at=>@after 1 second, self_destruct=>true to run some asynchronous SQL job in a function or trigger.

The only issue with this currently is it pollutes the timetable.base_task table and if I create another job with the same name this results in a unique constraint violation.

Could it make sense to optionally clean up the underlying base_task for self_destructing tasks?

**Comment by pashagolub** [comment]
The thing is another chain configs may depend on `base_taks` entries. Probably some cleaning query might be useful.

**Comment by a-mckinley** [comment]
Thanks @pashagolub on second thoughts I realised a better way to do this.

**Comment by pashagolub** [comment]
Can you please share your implementation?

**Comment by a-mckinley** [comment]
Hi @pashagolub 

Actually I created something more similar to the patterns in the samples.

One function to set up a parameterised base_task

```
create function setup_task_a()
$$
    -- delete base_task if exists
    -- create paramterised base_task and task_chain
$$;
```

And another to schedule a single instance of this task

```
create function schedule_task_a(params jsonb)
$$
    -- get chain_id
    -- create a chain_execution_config
    -- create chain execution parameters
    -- return chain_execution_config
$$;
```

Then call schedule_task_a() from a trigger or function.

This seems to be such a common pattern that I need I am thinking of wrapping this up into two higher level functions with approximately these signatures.

```
create function setup_new_base_task(base_task_name text,sql_script text,ignore_error boolean default true,autonomous boolean default false);

create function schedule_one_shot_base_task(base_task_name text,_interval timetable.cron,params jsonb);
```
All of these type of tasks are self_destruct by default.
