### ISSUE TITLE
success reported on failing chain

### ISSUE THREAD

**Issue by fluca1978** [cybertec-postgresql/pg_timetable#146]
**Describe the bug**
When a chain is failing the system reports it has been succesfully executed, while it should mention the chain has been executed but failed.

**To Reproduce**
1. schedule a failing command or script;
2. enabled verbose mode

An example of the output with a failing external script:

```
[ 2020-07-13 16:14:27.292 | LOG   ]: Number of active interval chains: 0
[ 2020-07-13 16:14:27.301 | ERROR ]: Task execution failed: {"ChainConfig":8,"ChainID":8,"TaskID":17,"TaskName":"TASK-2-PERIODIC","Script":"/tmp/scripts/task-2.sh","Kind":"SHELL","RunUID":{"String":"","Valid":false},"IgnoreError":true,"Autonomous":false,"DatabaseConnection":{"String":"","Valid":false},"ConnectString":{"String":"","Valid":false},"StartedAt":"2020-07-13T16:14:27.300222582+02:00","Duration":754}; Error: fork/exec /tmp/scripts/task-2.sh: permission denied
[ 2020-07-13 16:14:27.302 | LOG   ]: Executed successfully chain ID: 8; configuration ID: 8
```

**Comment by pashagolub** [comment]
Your chain has `IgnoreError = TRUE`. That means every execution is successful

**Comment by fluca1978** [comment]
Thanks.
Does it make sense to add this to the documentation ( see <https://github.com/cybertec-postgresql/pg_timetable/pull/147>)?
