### ISSUE TITLE
"Cannot log to the database: context deadline exceeded" on subsequent task runs

### ISSUE THREAD

**Issue by thormick** [cybertec-postgresql/pg_timetable#153]
**Description**
Output of tasks isn't logged to the timetable.log table on subsequent runs of a task; the first runs are OK, then "Cannot log to the database: context deadline exceeded" is logged on the console.

I'm not certain what triggers this, and hence how to reproduce this. I'm running a SQL task to create partitions, and which will log a NOTICE when partitions already exist. I've let it run for a while and it doesn't seem to recover once it enters this state.

**Log output**
Run with run_at set to NULL to run every minute for illustrating the issue.

[ 2020-08-27 12:47:19.584 | LOG   ]: Connection established...
[ 2020-08-27 12:47:19.584 | LOG   ]: Proceeding as 'timetable_worker' with client PID 1
[ 2020-08-27 12:47:19.597 | LOG   ]: Accepting asynchronous chains execution requests...
[ 2020-08-27 12:47:19.597 | LOG   ]: Checking for @reboot task chains...
[ 2020-08-27 12:47:19.599 | LOG   ]: Number of chains to be executed: 1
[ 2020-08-27 12:47:19.599 | LOG   ]: Checking for task chains...
[ 2020-08-27 12:47:19.600 | LOG   ]: Checking for interval task chains...
[ 2020-08-27 12:47:19.601 | LOG   ]: Number of chains to be executed: 1
[ 2020-08-27 12:47:19.604 | LOG   ]: Number of active interval chains: 0
[ 2020-08-27 12:47:19.606 | LOG   ]: Starting chain ID: 8; configuration ID: 11
[ 2020-08-27 12:47:19.609 | LOG   ]: Starting chain ID: 8; configuration ID: 12
[ 2020-08-27 12:47:19.610 | LOG   ]: Setting Role to meterology
[ 2020-08-27 12:47:19.613 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2020_08_01" already exists, skipping
[ 2020-08-27 12:47:19.613 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2020_09_01" already exists, skipping
[ 2020-08-27 12:47:19.614 | LOG   ]: Resetting Role
[ 2020-08-27 12:47:19.616 | LOG   ]: Setting Role to meterology
[ 2020-08-27 12:47:19.617 | LOG   ]: Executed successfully chain ID: 8; configuration ID: 11
[ 2020-08-27 12:47:19.618 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2020_08_01" already exists, skipping
[ 2020-08-27 12:47:19.619 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2020_09_01" already exists, skipping
[ 2020-08-27 12:47:19.619 | LOG   ]: Resetting Role
[ 2020-08-27 12:47:19.621 | LOG   ]: Executed successfully chain ID: 8; configuration ID: 12
[ 2020-08-27 12:48:19.604 | LOG   ]: Checking for task chains...
[ 2020-08-27 12:48:19.618 | LOG   ]: Checking for interval task chains...
[ 2020-08-27 12:48:19.619 | LOG   ]: Number of chains to be executed: 1
[ 2020-08-27 12:48:19.621 | LOG   ]: Number of active interval chains: 0
[ 2020-08-27 12:48:19.627 | LOG   ]: Starting chain ID: 8; configuration ID: 11
[ 2020-08-27 12:48:19.632 | LOG   ]: Setting Role to meterology
[ 2020-08-27 12:48:19.634 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2020_08_01" already exists, skipping
[ 2020-08-27 12:48:19.635 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2020_09_01" already exists, skipping
[ 2020-08-27 12:48:19.636 | LOG   ]: Resetting Role
[ 2020-08-27 12:48:19.638 | LOG   ]: Executed successfully chain ID: 8; configuration ID: 11
[ 2020-08-27 12:49:19.619 | LOG   ]: Checking for task chains...
[ 2020-08-27 12:49:19.633 | LOG   ]: Checking for interval task chains...
[ 2020-08-27 12:49:19.634 | LOG   ]: Number of chains to be executed: 1
[ 2020-08-27 12:49:19.635 | LOG   ]: Number of active interval chains: 0
[ 2020-08-27 12:49:19.643 | LOG   ]: Starting chain ID: 8; configuration ID: 11
[ 2020-08-27 12:49:19.645 | LOG   ]: Setting Role to meterology
[ 2020-08-27 12:49:19.647 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2020_08_01" already exists, skipping
[ 2020-08-27 12:49:19.647 | ERROR ]: Cannot log to the database: context deadline exceeded
[ 2020-08-27 12:49:19.647 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2020_09_01" already exists, skipping
[ 2020-08-27 12:49:19.647 | ERROR ]: Cannot log to the database: context deadline exceeded
[ 2020-08-27 12:49:19.647 | LOG   ]: Resetting Role
[ 2020-08-27 12:49:19.648 | LOG   ]: Executed successfully chain ID: 8; configuration ID: 11
[ 2020-08-27 12:50:19.635 | LOG   ]: Checking for task chains...
[ 2020-08-27 12:50:19.636 | LOG   ]: Checking for interval task chains...
[ 2020-08-27 12:50:19.637 | LOG   ]: Number of chains to be executed: 1
[ 2020-08-27 12:50:19.638 | LOG   ]: Number of active interval chains: 0
[ 2020-08-27 12:50:19.650 | LOG   ]: Starting chain ID: 8; configuration ID: 11
[ 2020-08-27 12:50:19.655 | LOG   ]: Setting Role to meterology
[ 2020-08-27 12:50:19.657 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2020_08_01" already exists, skipping
[ 2020-08-27 12:50:19.657 | ERROR ]: Cannot log to the database: context deadline exceeded
[ 2020-08-27 12:50:19.657 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2020_09_01" already exists, skipping
[ 2020-08-27 12:50:19.657 | ERROR ]: Cannot log to the database: context deadline exceeded
[ 2020-08-27 12:50:19.657 | LOG   ]: Resetting Role
[ 2020-08-27 12:50:19.661 | LOG   ]: Executed successfully chain ID: 8; configuration ID: 11

Only the first runs are indeed logged:
``` SQL
postgres=> SELECT * FROM timetable.log WHERE log_level != 'LOG' AND ts >= now() - '30 minute'::interval ORDER BY ts DESC limit 10;
  id   |              ts               |   client_name    | pid | log_level |                                          message                                          
-------+-------------------------------+------------------+-----+-----------+-------------------------------------------------------------------------------------------
 37723 | 2020-08-27 12:48:19.635563+00 | timetable_worker |   1 | USER      | Severity: NOTICE; Message: relation "lightning_month_2020_09_01" already exists, skipping
 37722 | 2020-08-27 12:48:19.634825+00 | timetable_worker |   1 | USER      | Severity: NOTICE; Message: relation "lightning_month_2020_08_01" already exists, skipping
 37713 | 2020-08-27 12:47:19.619225+00 | timetable_worker |   1 | USER      | Severity: NOTICE; Message: relation "lightning_month_2020_09_01" already exists, skipping
 37712 | 2020-08-27 12:47:19.618139+00 | timetable_worker |   1 | USER      | Severity: NOTICE; Message: relation "lightning_month_2020_08_01" already exists, skipping
 37708 | 2020-08-27 12:47:19.613945+00 | timetable_worker |   1 | USER      | Severity: NOTICE; Message: relation "lightning_month_2020_09_01" already exists, skipping
 37707 | 2020-08-27 12:47:19.613332+00 | timetable_worker |   1 | USER      | Severity: NOTICE; Message: relation "lightning_month_2020_08_01" already exists, skipping
(6 rows)
```
execution_log is correct:
``` SQL
postgres=> SELECT * FROM timetable.execution_log WHERE last_run >= now() - '30 minute'::interval ORDER BY last_run DESC;
 chain_execution_config | chain_id | task_id |           name           |                    script                     | kind |           last_run            |           finished            | returncode | pid | output |   client_name    
------------------------+----------+---------+--------------------------+-----------------------------------------------+------+-------------------------------+-------------------------------+------------+-----+--------+------------------
                     11 |        8 |      14 | CreateLightningPartition | CALL meterology.create_lightning_partitions() | SQL  | 2020-08-27 12:50:19.655466+00 | 2020-08-27 12:50:19.65922+00  |          0 |   1 |        | timetable_worker
                     11 |        8 |      14 | CreateLightningPartition | CALL meterology.create_lightning_partitions() | SQL  | 2020-08-27 12:49:19.646018+00 | 2020-08-27 12:49:19.647791+00 |          0 |   1 |        | timetable_worker
                     11 |        8 |      14 | CreateLightningPartition | CALL meterology.create_lightning_partitions() | SQL  | 2020-08-27 12:48:19.632418+00 | 2020-08-27 12:48:19.637294+00 |          0 |   1 |        | timetable_worker
                     12 |        8 |      14 | CreateLightningPartition | CALL meterology.create_lightning_partitions() | SQL  | 2020-08-27 12:47:19.6162+00   | 2020-08-27 12:47:19.620595+00 |          0 |   1 |        | timetable_worker
                     11 |        8 |      14 | CreateLightningPartition | CALL meterology.create_lightning_partitions() | SQL  | 2020-08-27 12:47:19.611106+00 | 2020-08-27 12:47:19.61568+00  |          0 |   1 |        | timetable_worker
```

**Comment by pashagolub** [comment]
Hello. Are you using stable release or the latest version based on `master`?

**Comment by thormick** [comment]
Oh yeah, totally forgot about versions. I'm using the cybertecpostgresql/pg_timetable:latest docker image.

Which I now realize is the "latest", and I should be pinning it (I copied the instructions from the readme when I started playing around, and when I moved to production I copied my work without thinking of the version, so the tag has just been tagging along). I imagine I should be using "v2.3.0"?

**Comment by pashagolub** [comment]
Thanks for the info. The "latest" means development version based on `master`. 

Released versions are marked as `vX.X.X`, e.g. `v2.3.0`. And the images for branches are named the same as branches.

Details: https://hub.docker.com/repository/docker/cybertecpostgresql/pg_timetable

If you want to try against official release, please, try with `v2.3.0`, but anyway thanks for your report. We're on it.

**Comment by thormick** [comment]
Thanks for the info. I'm used to "latest" meaning latest official release. Will try with v2.3.0.

And you're welcome, always happy to report what I find.

**Comment by pashagolub** [comment]
Be aware that the latest version might change underlying database schema

**Comment by thormick** [comment]
Thanks, noted.

**Comment by thormick** [comment]
Checked it with `v2.3.0`, seeing the same error on that version too.

**Comment by pashagolub** [comment]
Thanks. Can we have SQL of tasks failed for tests? Or similar to reproduce the issue. 

Thanks in advance

**Comment by thormick** [comment]
Sure, even if it's so extremely straight forward I'm not sure what could trigger it in my code.
I have a script to add partitions:
```SQL
CREATE OR REPLACE PROCEDURE meterology.create_lightning_partitions( period date DEFAULT current_date )
AS $$
DECLARE
cmd TEXT := 'CREATE TABLE IF NOT EXISTS meterology.lightning_month_%s PARTITION OF meterology.lightning
             FOR VALUES FROM (''%s'') TO (''%s'')';
month1 TEXT := date_trunc('month', period)::DATE::TEXT;
month2 TEXT := (date_trunc('month', period) + '1 month')::DATE::TEXT;
month3 TEXT := (date_trunc('month', period) + '2 month')::DATE::TEXT;
BEGIN
  EXECUTE FORMAT(cmd, translate(month1,'-','_'), month1, month2);
  EXECUTE FORMAT(cmd, translate(month2,'-','_'), month2, month3);
END
$$ LANGUAGE plpgsql;
```
And add a job to run it monthly, though I replace ```'@every 1 month'``` with ```NULL``` for testing:
```SQL
WITH
sql_task(id) AS (
    INSERT INTO timetable.base_task VALUES (
        DEFAULT,                       -- task_id
        'CreateLightningPartition',    -- name
        DEFAULT,                       -- 'SQL' :: timetable.task_kind
        'CALL meterology.create_lightning_partitions()' -- task script
    )
    RETURNING task_id
),
chain_insert(chain_id) AS (
    INSERT INTO timetable.task_chain
        (chain_id, parent_id, task_id, run_uid, database_connection, ignore_error)
    VALUES
        (DEFAULT, NULL, (SELECT id FROM sql_task), 'meterology', NULL, TRUE)
    RETURNING chain_id
)
INSERT INTO timetable.chain_execution_config (
    chain_id,
    chain_name,
    run_at,
    max_instances,
    live,
    self_destruct,
    exclusive_execution)
 VALUES (
    (SELECT chain_id FROM chain_insert), -- chain_id,
    'CreateLightningPartition', -- chain_name,
    '@every 1 month', -- run_at,
    1, -- max_instances,
    TRUE, -- live,
    FALSE, -- self_destruct,
    FALSE
);
```

**Comment by pashagolub** [comment]
Will try to face this problem by refactoring log machinery in #158. Thanks for your help and stay tuned.

**Comment by thormick** [comment]
Great! Always happy to help.

**Comment by pashagolub** [comment]
Hello @thormick,

Any news on this?

**Comment by thormick** [comment]
I've checked it again today with both `3.1` and what is right now `latest`, but I'm getting the same issue:

```
[ 2021-01-14 13:10:15.229 | LOG   ]: Connection established...
[ 2021-01-14 13:10:15.229 | LOG   ]: Proceeding as 'timetable_worker' with client PID 1
[ 2021-01-14 13:10:15.233 | LOG   ]: Accepting asynchronous chains execution requests...
[ 2021-01-14 13:10:15.248 | LOG   ]: Checking for @reboot task chains...
[ 2021-01-14 13:10:15.263 | LOG   ]: Number of chains to be executed: 0
[ 2021-01-14 13:10:15.275 | LOG   ]: Checking for task chains...
[ 2021-01-14 13:10:15.289 | LOG   ]: Checking for interval task chains...
[ 2021-01-14 13:10:15.302 | LOG   ]: Number of chains to be executed: 1
[ 2021-01-14 13:10:15.304 | LOG   ]: Number of active interval chains: 0
[ 2021-01-14 13:10:15.321 | LOG   ]: Starting chain ID: 2; configuration ID: 3
[ 2021-01-14 13:10:15.370 | LOG   ]: Setting Role to meterology
[ 2021-01-14 13:10:15.384 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2021_01_01" already exists, skipping
[ 2021-01-14 13:10:15.405 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2021_02_01" already exists, skipping
[ 2021-01-14 13:10:15.421 | LOG   ]: Resetting Role
[ 2021-01-14 13:10:15.460 | LOG   ]: Executed successfully chain ID: 2; configuration ID: 3
[ 2021-01-14 13:11:15.303 | LOG   ]: Checking for task chains...
[ 2021-01-14 13:11:15.400 | LOG   ]: Checking for interval task chains...
[ 2021-01-14 13:11:15.401 | LOG   ]: Number of chains to be executed: 1
[ 2021-01-14 13:11:15.565 | LOG   ]: Number of active interval chains: 0
[ 2021-01-14 13:11:15.578 | LOG   ]: Starting chain ID: 2; configuration ID: 3
[ 2021-01-14 13:11:15.645 | LOG   ]: Setting Role to meterology
[ 2021-01-14 13:11:15.661 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2021_01_01" already exists, skipping
[ 2021-01-14 13:11:15.667 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2021_02_01" already exists, skipping
[ 2021-01-14 13:11:15.678 | LOG   ]: Resetting Role
[ 2021-01-14 13:11:15.712 | LOG   ]: Executed successfully chain ID: 2; configuration ID: 3
[ 2021-01-14 13:12:15.563 | LOG   ]: Checking for task chains...
[ 2021-01-14 13:12:15.570 | LOG   ]: Checking for interval task chains...
[ 2021-01-14 13:12:15.571 | LOG   ]: Number of chains to be executed: 1
[ 2021-01-14 13:12:15.584 | LOG   ]: Number of active interval chains: 0
[ 2021-01-14 13:12:15.594 | LOG   ]: Starting chain ID: 2; configuration ID: 3
[ 2021-01-14 13:12:15.646 | LOG   ]: Setting Role to meterology
[ 2021-01-14 13:12:15.658 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2021_01_01" already exists, skipping
[ 2021-01-14 13:12:15.658 | ERROR ]: Cannot log to the database: 
%!(EXTRA context.deadlineExceededError=context deadline exceeded)[ 2021-01-14 13:12:15.658 | USER  ]: Severity: NOTICE; Message: relation "lightning_month_2021_02_01" already exists, skipping
[ 2021-01-14 13:12:15.658 | ERROR ]: Cannot log to the database: 
%!(EXTRA context.deadlineExceededError=context deadline exceeded)[ 2021-01-14 13:12:15.658 | LOG   ]: Resetting Role
[ 2021-01-14 13:12:15.686 | LOG   ]: Executed successfully chain ID: 2; configuration ID: 3
```

**Comment by pashagolub** [comment]
Is it possible that the connection number is limited for the `pg_timetable` user? Can you see any errors in the server logs?

**Comment by thormick** [comment]
Thanks. In what is now the `latest` docker image release I'm no longer seeing this error.

**Comment by pashagolub** [comment]
Great!!! Thanks a lot for your help.
