### ISSUE TITLE
Tasks on Remote DB

### ISSUE THREAD

**Issue by witaki** [cybertec-postgresql/pg_timetable#161]
SQL tasks to execute on RemoteDB doesn't work

Hi, I'm trying to execute functions/insert data in another DB that doesn't is the pg_timetable config DB.
The agent connects on my remote database, but it doesn't find neither my functions or tables on the remote host.

In another way, if I configure the chain task to execute on remote DB but in the script I use a local table(this table doesn't exists on the remote db), it executes ok saving the records on the local table.

**Comment by pashagolub** [comment]
Hello,

we have fixed this issue in #165 and release the new version.

Thanks in advance!
