### ISSUE TITLE
Can not remote to other server

### ISSUE THREAD

**Issue by tunh** [cybertec-postgresql/pg_timetable#164]
I always get result `pq: relation "public.user_account" does not exist` when using remote SQL.

`base_task` table:
```
INSERT INTO timetable.base_task (task_id, name, kind, script) VALUES (6, 'Remote SQL', 'SQL', 'SELECT * FROM public.user_account;');
```

`database_connection` table:
```
INSERT INTO timetable.database_connection (database_connection, connect_string, comment) VALUES (1, 'host=127.0.0.1 port=5432 dbname=abcxyz user=application password=p4ssw0rd sslmode=disable', 'abcxyz@127.0.0.1/32');
```

`task_chain` table:
```
INSERT INTO timetable.task_chain (chain_id, parent_id, task_id, run_uid, database_connection, ignore_error, autonomous) VALUES (1, null, 6, null, 1, true, false);
```

`chain_execution_config` table:
```
INSERT INTO timetable.chain_execution_config (chain_execution_config, chain_id, chain_name, run_at, max_instances, live, self_destruct, exclusive_execution, excluded_execution_configs, client_name) VALUES (1, 1, 'truncate_deal_user', '* * * * *', 1, true, false, false, null, null);
```

**Comment by pashagolub** [comment]
Hello,

this error means the target table doesn't exist. I would check connection credentials in this particular case. Are they correct?

**Comment by tunh** [comment]
It works only if public.* schema and timetable.* schema in the same database.
It doesn't work when I separated 2 difference databases. It seems timetable.database_connection doesn't be used?

**Comment by pashagolub** [comment]
Could you please provide us with logs? In case of error it should contain `Error in remote connection` message and in case of success `Remote Connection established...`

**Comment by tunh** [comment]
There is no error log. You can reproduce the bug as following:
1. Create new database `timetable` for pg_timetable.
2. Create new schema `timetable.public.deal_user`
3. Create new database `abcxyz` for application.
4. Create new schema `abcxyz.public.deal_user`

pg_timetable query `timetable.public.deal_user` not `abcxyz.public.deal_user`. I think there are some error when you process connection string `timetable.database_connection`

**Comment by pashagolub** [comment]
Thanks a lot for your help. We have fixed this issue here #165

**Comment by pashagolub** [comment]
https://github.com/cybertec-postgresql/pg_timetable/releases/tag/v2.4.0

**Comment by tunh** [comment]
Awesome @pashagolub , very responsive! Now I can you `pg_timetable` for production.

**Comment by pashagolub** [comment]
Thanks a lot for your help!
