### ISSUE TITLE
remove duplicate GitHub Actions run for push and pull-request

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pg_timetable#197]
smart [solution](https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/10) by @piersy allows eliminating duplicates

**Comment by pashagolub** [comment]
Closed by #196

**Comment by piersy** [comment]
@pashagolub My apologies, I don't think that solution actually works, I've written a reply [here](https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/13?u=piersy) explaining my findings.

**Comment by pashagolub** [comment]
Thanks. Will check that.

**Comment by pashagolub** [comment]
Yes, it seems you're correct. Forked PR doesn't trigger the action. Need to find another solution. Thanks anyway! :)
