### ISSUE TITLE
chain_id can be NULL

### ISSUE THREAD

**Issue by LorenzHenk** [cybertec-postgresql/pg_timetable#207]
**Describe the bug**

`timetable.chain_execution_config.chain_id` is nullable, but pg_timetable actually expects it to be not null.

**To Reproduce**
1. insert
```sql
INSERT INTO timetable.chain_execution_config (chain_id, chain_name, max_instances, live)
				VALUES (NULL, 'Send Mail', 1, TRUE);
```
2. check pg_timetable logs
3. wait for next cron run

```
Could not query pending tasks: sql: Scan error on column index 1, name "chain_id": converting NULL to int is unsupported
```

**Expected behavior**

I don't think `chain_execution_config` without a chain makes sense, so the column should be `NOT NULL`.

**Screenshots**

![image](https://user-images.githubusercontent.com/10603631/109169366-03e83180-7780-11eb-97a5-a16a07050eb8.png)

**Comment by pashagolub** [comment]
Thanks for the report! I decided not to change the schema but add an additional check to the SQL statement.
I think configuration items with NULL `chain_id` may be considered as templates and used later in some kind of GUI.
