### ISSUE TITLE
client name with dashes doesnt work 

### ISSUE THREAD

**Issue by adulion2** [cybertec-postgresql/pg_timetable#214]
I added a client name through the ENV variable PGTT_CLIENTNAME that had dashes and it failed to connect to the db- 

Removing the dashes got it working

version 3.2 running on AWS ECR/fargate

**Comment by pashagolub** [comment]
Thanks for your report. Would you, please, provide some logs with the error messages. 
Thank you so much for your attention and participation.

**Comment by adulion2** [comment]
Sure:

`m2021-03-03 11:32:26.125 | ERROR[0m ]: failed to connect to `host=xx.eu-west-2.compute.amazonaws.com user=user database=abc`: AfterConnect error (ERROR: syntax error at or near "-" (SQLSTATE 42601))`
