### ISSUE TITLE
Crypt the password for connection

### ISSUE THREAD

**Issue by p0mp0k0** [cybertec-postgresql/pg_timetable#229]
Password for connection should be crypted as a crontab job in bat, cmd, sh, etc.. 
Pg_timetable is a good tool for console command, but as a crontab job, it is not confortable, the password is plaintext, so it can be occupied.

**Comment by pashagolub** [comment]
Hello. Thanks for your request. You can pass the password as an environmental variable. Can this help?

**Comment by ukolovda** [comment]
Hi!
I made .pgpass file: https://www.postgresql.org/docs/current/libpq-pgpass.html
But it not worked. 
`psql` can use it, but `pg_timetable` does not.

You can use environment variable:
`export PGTT_URL=postgresql://user:password@localhost/database

**Comment by pashagolub** [comment]
Yes, and you can use `PGTT_PASSWORD` env var. I will check the possibility for `.pgpass`. 
Thanks for the idea.
