### ISSUE TITLE
Documentation request - how to run pg_timetable

### ISSUE THREAD

**Issue by Deracination** [cybertec-postgresql/pg_timetable#301]
**Is your feature request related to a problem? Please describe.**
It's unclear to me from the documentation how to actually run pg_timetable: does pg_timetable executable need to be run from cron on a regular basis to execute jobs or it is run just once and then somehow a scheduler runs entirely within the db?

**Describe the solution you'd like**
Would like documentation to explain how to run the scheduler and what it's doing

**Comment by pashagolub** [comment]
Hello.

Thanks for your question. In the [Quick Start](https://pg-timetable.readthedocs.io/en/v4_dev/README.html#quick-start) section of the manual there is a command to run `pg_timetable`:

```sh
# pg_timetable postgresql://scheduler:somestrong@localhost/my_database --clientname=vacuumer
```

How do you think where should we duplicate this info to prevent such misunderstandings in the future?

Regards

**Comment by Deracination** [comment]
Hi, it's not clear to me if this is a one-off command (that sets the scheduler running inside the db somehow?) or something that must be run regularly from cron. What does the pg_timetable command actually do?

**Comment by pashagolub** [comment]
Hi,

`pg_timetable` is the standalone scheduler that runs separately on its own.

> that sets the scheduler running inside the db somehow?

No, `pg_timetable` is the separate process that communicates to the PostgreSQL database and executes jobs.

> What does the pg_timetable command actually do?

It launches `pg_timetable` process. No *cron* or any other 3rd party software needed. `pg_timetable` runs forever and responsible for everything.

> it's not clear to me if this is a one-off command

Yes, this is one command. Usually, you put it somewhere to launch `pg_timetable` at the start of the OS.

**Comment by Deracination** [comment]
Thank you, that was the key bit of information I was missing - that pg_timetable runs forever.
