### ISSUE TITLE
Simple cron jobs not working

### ISSUE THREAD

**Issue by gherandy** [cybertec-postgresql/pg_timetable#305]
**Describe the bug**
I have created some simple test jobs to play with the latest v4 version and they failed to execute.

**To Reproduce**
0. Have a working Postgresql v12 ready
1. Download the latest version of pg_timetable (v4.0.0 at that time)
2. Run init command `.\pg_timetable.exe postgresql://{your_postgresql_user}:{your_postgresql_user_password}@127.0.0.1:5432/{your_db} --clientname=TimetableClient --init`
3. Run pg_timetable `.\pg_timetable.exe postgresql://{your_postgresql_user}:{your_postgresql_user_password}@127.0.0.1:5432/{your_db} --clientname=TimetableClient`
4. Log in into postgresql with your postgresql user and add a job `select timetable.add_job('Job1','*/2 * * * *', 'INSERT INTO some_table({some columns}) VALUES({some values})');`
5. Check pg_timetable logs

**Expected behavior**
The insert should happen every 2 minutes.

**Actual behavior**
The job is created successfully. 
It also inserts a line into timetable.parameter with null as the parameter value. This causes this exception:
`[31m [ERROR] [chain:1] [task:1] [sql:SELECT value FROM timetable.parameter WHERE chain_id = $1 AND task_id = $2 ORDER BY order_id ASC] [args:[1 1]] [err:can't scan into dest[0]: cannot scan null into *string] [pid:9488] ←[0mQuery
2021-08-04 14:03:28.337←[31m [ERROR] [chain:1] [task:1] [error:scany: scan row value into a primitive type: can't scan into dest[0]: cannot scan null into *string] ←[0mcannot fetch parameters values for chain: scany: scan row value into a primitive type: can't scan into dest[0]: cannot scan null into *string
`

If I remove this line from the timetable.parameter, this exception goes away and my job starts to execute every minute instead of every 2 minutes.

**Desktop (please complete the following information):**
 - OS: Windows 10 and Ubuntu 20.04 LTS
 - Version pg_timetable V4.0.0

**Additional information**
I have tested the same job but with "@every 2 minutes" instead of "*/2 * * * *" and after removing the timetable.parameter line (with null value) the job executed every 2 minutes.

**Comment by pashagolub** [comment]
Hello.

Thanks a lot for your report. I confirm both bugs. 

Stay tuned.
