### ISSUE TITLE
How to run task every N seconds?

### ISSUE THREAD

**Issue by ukolovda** [cybertec-postgresql/pg_timetable#307]
**Is your feature request related to a problem? Please describe.**
Can I run task, for example, every 10 seconds? In my project I need push SMS or e-mail from queue table, and I want run it faster then every minute.

**Describe the solution you'd like**
It can be extended time format with additional parameter at start, i.e. 
`*/10s * * * * *`
or other

**Describe alternatives you've considered**
I can make cycle in code with sleep between running main task.

**Additional context**

**Comment by pashagolub** [comment]
Hello, you can try interval chains (jobs), e.g. `@every 10 seconds`
