### ISSUE TITLE
Add delete_job(job_name) function as opposite for add_job()

### ISSUE THREAD

**Issue by ukolovda** [cybertec-postgresql/pg_timetable#323]
**Is your feature request related to a problem? Please describe.**
I need ability to delete entire job.

**Describe the solution you'd like**
New documented function `timetable.delete_job(job_name)` which will delete chain and it's tasks.

**Describe alternatives you've considered**
I can delete rows from tables, but this require knowledge of internal structure.

**Comment by pashagolub** [comment]
Thanks a lot for your proposal. Seems legit!
