### ISSUE TITLE
Allow week day in symbol format as: `0 0 * * SUN`

### ISSUE THREAD

**Issue by ukolovda** [cybertec-postgresql/pg_timetable#331]
**Is your feature request related to a problem? Please describe.**
I've got the error `value for domain timetable.cron violates check constraint "cron_check"` for schedule '18 5 * * SUN'

**Describe the solution you'd like**
I thing, scheduler should recognize week days: MON-SUN

**Describe alternatives you've considered**
I can manual convert day names to number, but this expression can be less clearly.

**Comment by pashagolub** [comment]
yeah, crontab is cool! :) But it's an overkill for us, I suppose.
