### ISSUE TITLE
Feature request: Immediate executing of new jobs

### ISSUE THREAD

**Issue by ukolovda** [cybertec-postgresql/pg_timetable#348]
**Is your feature request related to a problem? Please describe.**
Sometimes I need run job "as soon as possible", not waiting up to 60 seconds to refetch chains.

**Describe the solution you'd like**
Scheduler should load new chain and tasks as soon as it was append to table.
My be, we can use notifications from table triggers (after commit of transaction).

**Describe alternatives you've considered**
Decrease refetch interval in source code, but this will increase database loading.

**Comment by pashagolub** [comment]
Hello.

Have you tried `timetable.notify_chain_start(chain_id BIGINT, worker_name TEXT)` [function](https://pg-timetable.readthedocs.io/en/master/database_schema.html#jobs-related-functions)? I believe it's fast enough for the most of requirements.

I'm not sure we should load as soon as possible. `pg_timetable` is a scheduler not a real-time queue processing software. For async processing, [PGQ](https://wiki.postgresql.org/wiki/PGQ_Tutorial) is the first what I'm thinking about. But there are a lot more nowadays. Should check the situation.
