### ISSUE TITLE
Too big `run_status` table after some time

### ISSUE THREAD

**Issue by ukolovda** [cybertec-postgresql/pg_timetable#370]
**Is your feature request related to a problem? Please describe.**
The service insert many rows in the table `run_status` (one row when starting and  one when finished). Over time it contains too many rows (about 3M rows in my test system). 
Function `get_chain_running_statuses` works too slow (~2-3 seconds for each call). CPU usage too high.

**Describe the solution you'd like**
I need procedure for remove old rows from `run_status` table. It can be started by schedule. It may be built-in internal command or stored function (preferred), or both.

As I think, the query is:
```sql
delete from timetable.run_status
where run_status_id in (
  select unnest( array[ start_status.run_status_id, finish_status.run_status_id ] )
  from timetable.run_status start_status
         join timetable.run_status finish_status
              on start_status.run_status_id = finish_status.start_status_id
                AND finish_status.execution_status IN ('CHAIN_FAILED', 'CHAIN_DONE', 'DEAD')
  WHERE start_status.execution_status = 'CHAIN_STARTED'
);
```
Please, correct me if it is wrong.

**Describe alternatives you've considered**
Manual delete old rows from table `run_status` (see query above).

**Additional context**
Explain plan is:
![изображение](https://user-images.githubusercontent.com/1921594/148358756-50f2e543-1bc9-425e-a2f5-414be7cdcb47.png)

**Comment by pashagolub** [comment]
Hello.

Thanks a lot for your help. Would you please provide the exact `EXPLAIN` plan as a text?

I'm wondering if we can just solve this by making `run_status` table unlogged...

**Comment by ukolovda** [comment]
Raw plain is:

```
QUERY PLAN
Gather Merge  (cost=109797.43..117610.44 rows=66964 width=8) (actual time=1252.516..1281.294 rows=0 loops=1)
  Workers Planned: 2
  Workers Launched: 2
  ->  Sort  (cost=108797.41..108881.11 rows=33482 width=8) (actual time=1169.984..1169.989 rows=0 loops=3)
        Sort Key: start_status.run_status_id
        Sort Method: quicksort  Memory: 25kB
        Worker 0:  Sort Method: quicksort  Memory: 25kB
        Worker 1:  Sort Method: quicksort  Memory: 25kB
        ->  Parallel Hash Anti Join  (cost=54481.34..106281.05 rows=33482 width=8) (actual time=1169.834..1169.838 rows=0 loops=3)
              Hash Cond: (start_status.run_status_id = finish_status.start_status_id)
              ->  Parallel Seq Scan on run_status start_status  (cost=0.00..49445.68 rows=42900 width=8) (actual time=0.040..362.015 rows=34128 loops=3)
                    Filter: ((execution_status = 'CHAIN_STARTED'::timetable.execution_status) AND (chain_id = 6))
                    Rows Removed by Filter: 935055
              ->  Parallel Hash  (cost=47930.79..47930.79 rows=399244 width=8) (actual time=656.807..656.808 rows=323031 loops=3)
                    Buckets: 131072  Batches: 16  Memory Usage: 3424kB
                    ->  Parallel Seq Scan on run_status finish_status  (cost=0.00..47930.79 rows=399244 width=8) (actual time=23.635..505.711 rows=323031 loops=3)
"                          Filter: (execution_status = ANY ('{CHAIN_FAILED,CHAIN_DONE,DEAD}'::timetable.execution_status[]))"
                          Rows Removed by Filter: 646152
Planning Time: 0.898 ms
JIT:
  Functions: 39
"  Options: Inlining false, Optimization false, Expressions true, Deforming true"
"  Timing: Generation 6.426 ms, Inlining 0.000 ms, Optimization 2.939 ms, Emission 66.532 ms, Total 75.897 ms"
Execution Time: 1346.282 ms
```

I think, if we make the table `unlogged`, it does not help. The query select all `started` rows and then exclude all `finished`. when it contains many rows, I don't see other way for speed up. Only delete old non-valued rows.

**Comment by pashagolub** [comment]
> I think, if we make the table unlogged, it does not help. The query select all started rows and then exclude all finished. when it contains many rows, I don't see other way for speed up. Only delete old non-valued rows.

Yeah, I forgot to add about the deletion. And to not produce WALs during these operations my second thought was to make the table unlogged. :)

**Comment by pashagolub** [comment]
Just leave it here for further investigations https://explain.depesz.com/s/lwN2

**Comment by ukolovda** [comment]
Thank you!

Also it is small optimization, but I can decrease table size about 10% if column `execution_status` make after `created_at`. Now column execution_status take 8 bytes because next column `chain_id bigint` must be alignment by 8 bytes.

In my case with original col positions table size is 560 Mb, and with new position - 508 Mb.

```sql
create table timetable.run_status_origin as select
  run_status_id,
  start_status_id,
  execution_status,
  chain_id,
  task_id,
  created_at,
  client_name
from timetable.run_status;
```
```sql
create table timetable.run_status_new_pos as select
  run_status_id,
  start_status_id,
  chain_id,
  task_id,
  created_at,
  execution_status,
  client_name
from timetable.run_status;
```

```sql
SELECT
  schema_name,
  relname,
  pg_size_pretty(table_size) AS size,
  table_size
FROM (
       SELECT
         pg_catalog.pg_namespace.nspname           AS schema_name,
         relname,
         pg_relation_size(pg_catalog.pg_class.oid) AS table_size
       FROM pg_catalog.pg_class
              JOIN pg_catalog.pg_namespace ON relnamespace = pg_catalog.pg_namespace.oid
     ) t
WHERE schema_name NOT LIKE 'pg_%'
ORDER BY table_size DESC;
```

```
schema_name,relname,size,table_size
timetable,run_status,564 MB,590872576
timetable,run_status_origin,560 MB,586874880
timetable,run_status_new_pos,508 MB,532652032

``

**Comment by ukolovda** [comment]
I think, better solution will be periodic deleting old rows from engine himself.
It can use `client_name` value and delete only own rows, for prevent locks if other instance also start deleting. Every instance should delete only own rows.
We can use internal counter and run clearing operation when it exceed some limit - for example, every 1000 executed chains. In my case deleting of 6K rows take about 4 seconds.

**Comment by ukolovda** [comment]
I made simpler query. Because we have a cascade constraint, we shouldn't delete child (finishing) row, it will be delete automaticaly:
```sql
delete from timetable.run_status
where run_status_id in (
  select start_status.run_status_id
  from timetable.run_status start_status
         join timetable.run_status finish_status
              on start_status.run_status_id = finish_status.start_status_id
                AND finish_status.execution_status IN ('CHAIN_FAILED', 'CHAIN_DONE', 'DEAD')
  WHERE start_status.execution_status = 'CHAIN_STARTED'
);
```


Also index by `start_status_id` dramatically reduce delete time (several seconds vs tens minutes for 100k rows).

**Comment by petr-klinger** [comment]
The solution to the problem is to prevent it. I remove all unnecessary rows from the execution_log and run_status tables as soon as they are no longer needed:

Trigger AFTER INSERT ON timetable.run_status:
   if new.execution_status::varchar in ('CHAIN_DONE') then
    delete from timetable.run_status
     where chain_id=new.chain_id and
           (start_status_id<>new.start_status_id or
            (run_status_id<>new.start_status_id and start_status_id is null));
   end if;        
   return new;    


BEFORE INSERT ON timetable.execution_log:
   delete from timetable.execution_log
    where timetable.execution_log.chain_id=new.chain_id

**Comment by pashagolub** [comment]
Thanks, both of you, for your help. 

We implemented the `run_status` table this way because thought it might be useful for monitoring and retrospective analysis. But assuming we have full log stored in `log` and `execution_log` the following changes are coming to mind:

1. Instead of adding the `CHAIN_DONE` status row, just delete previous rows for the current chain.
2. Make `run_status` as `UNLOGGED` to prevent WAL production.

I will investigate this possibility further to make sure it won't break anything, especially the simplicity of the analysis.

**Comment by petr-klinger** [comment]
I intentionally leave either all records in the run_status table if the job did not end "CHAIN_DONE" to analyze the reasons for the errors, or at least the last run of the job to show times that are not saving in the execution_log table for the last job (TASK). I plead always for at least one group of records for each chain_id in RUN_STATUS.

**Comment by ukolovda** [comment]
As I understand, we don't `delete` because it can lock the table. `Inserts` is more safe. but it make too mane rows.

**Comment by pashagolub** [comment]
Can you please check #382

**Comment by ukolovda** [comment]
Thank you! I will try it some later...
