### ISSUE TITLE
Table RUN_STATUS

### ISSUE THREAD

**Issue by petr-klinger** [cybertec-postgresql/pg_timetable#394]
I work with version 4.4. TT and dropping the RUN_STATUS table seems to me to be wrong. If a long-running task is running, it is not possible to quickly determine when it was actually run, there is no (not even one-sided) record in EXECUTION_LOG before completion. The same is true when you set up only one task to run and use the ADD_JOB function based on concurrent conditions, such as a server backup in hours. Is the job already added? I suggest returning the RUN_STATUS table and dropping all previous records for this chain_id when writing a record with exexution_status 'CHAIN_DONE', 'CHAIN_FAILED' or 'DEAD'. This preserves all the necessary information for the unfinished task. Alternatively, I am solving the situation by adding a TS column with a default value of NOW () to the new ACTIVE_CHAIN ​​table, so that you can at least see when the task started. I know that the necessary data can be found in the LOG table, but for a quick search there are missing indexed columns CHAIN_ID and TASK_ID and again it will bother that the table is large. Thank you for considering your objection.

**Comment by pashagolub** [comment]
thanks for your thoughts.

Did you try to observe long-running tasks in the `active_chain` table? Maybe it's a good idea to add a timestamp to it anyway.

Would you please provide an example of concurrent jobs and `add_job()` function? I'm afraid I don't quite understand it.

**Comment by pashagolub** [comment]
One side notice. I don't think we should restore the `run_status` table. It was a pain in the ass. But I do think we should improve observability.

**Comment by petr-klinger** [comment]
We monitor jobs from active_chain, but if there is a timestamp for a job running for example two hours (server backup at our customers), it sees that the backup is running, but has no idea how long.

The user has an interface that displays the status of TT tables and the status of task execution. However, it may happen that it needs to perform one of the tasks (transfer of data from state code lists of the state administration, etc.) immediately. It is therefore set to the position of the appropriate row (above the CHAIN ​​table) and gives the operator the command that he wants to perform this task outside the schedule - using the ADD_JOB function. But on the server, for example, there is a two-hour backup of the SQL server and the user does not know whether he submitted his request or not. (So ​​far I am solving another variable ADD_CHAIN ​​and another record in ACTIVE_CHAIN, where this request is written instead of the variable CHAIN_ID to ADD_CHAIN ​​(including the time of the request in the TS column) and then in the trigger to delete for CHAIN_ID will delete records with the same ID in the ADD_CHAIN ​​column Thus, by scanning the ACTIVE_CHAIN ​​table and new variables, it is possible to maintain a certain overview for interactive users over the TT system, but the original RUN_STATUS table, where all events for unfinished tasks were written (ie in our country up to 20 sentences), does not match.

This is not the name of the table, but it was invaluable and very fast in terms of information when modifying its behavior, when it had only work-in-progress. If no job was performed, it contained 0 records.
