### ISSUE TITLE
ERROR "Failed to set current task contexttx is closed"

### ISSUE THREAD

**Issue by drenbutkovic** [cybertec-postgresql/pg_timetable#541]
Hi,
error _"Failed to set current task contexttx is closed"_ is logged in table **timetable.log** when task is configured to be executed on **external** database. 
The task is completed **successfully**, but an error is shown in the log.
The task from the example is executed every minute, but the behavior is the same for tasks that are started in some other periods.
If the task is defined in a way that it is executed on the same DB where is pg_timetable then there is no error in log.
ERROR message is between messages "_Remote connection established..._"  and "_Closing remote session_".

Timetable database and external database is on same Postgres cluster.
Timetable version: pg_timetable:5.1
OS: CentOS Linux release 7.9.2009 (Core)
Postgres: PostgreSQL 11.11

Task definition
![task_definition](https://user-images.githubusercontent.com/41565252/220884810-e39909c4-e2dd-4127-b071-c242804443a5.png)

database_connection is in format 
postgres://username:password@ipaddress:port/database_name?sslmode=disable

Chain definition
![chain_definition](https://user-images.githubusercontent.com/41565252/220879901-9ffd661f-62a0-4040-9da2-7e7897774c18.png)

Logs from **execution_log** table
![execution_log](https://user-images.githubusercontent.com/41565252/220879989-ed220204-603c-4e0c-a979-9ada9bdd87dc.png)

Logs from **log** table
![logs](https://user-images.githubusercontent.com/41565252/220880066-c5f11f04-5c1d-429b-994f-9c6aebb318d4.png)

All podman logs for one chain.
[podman_logs_chain_147.txt](https://github.com/cybertec-postgresql/pg_timetable/files/10812497/podman_logs_chain_147.txt)

pg_timetable service
[pg_timetable_v5_service_podman_conf.txt](https://github.com/cybertec-postgresql/pg_timetable/files/10812651/pg_timetable_v5_service_podman_conf.txt)

**Comment by pashagolub** [comment]
Hello. Thanks for your request.

Would you, please, be so kind to add `--log-level=debug` start parameter and provide the output here. 
File `/etc/systemd/system/pg_timetable_v5.service` will look like this probably:
```ini
[Unit]
Description=pg_timetable
Wants=network.target postgresql-11.service
After=network-online.target postgresql-11.service

[Service]
Restart=on-failure
ExecStartPre=/usr/bin/rm -f /%t/%n-pid /%t/%n-cid
ExecStart=/usr/bin/podman run --conmon-pidfile  /%t/%n-pid  --cidfile /%t/%n-cid -d --name pg_timetable-v5 \
-e PGTT_PGHOST=192.168.50.97 \
-e PGTT_PGPORT=5432 \
-e PGTT_PGDATABASE=timetablev5 \
-e PGTT_PGUSER=timetable \
-e PGTT_PGPASSWORD=xxxxx \
-e PGTT_RESTPORT=8111 \
--net=host \
-p 8111:8111 \
-v /etc/localtime:/etc/localtime:ro \
cybertecpostgresql/pg_timetable:5.1 \
-c umbosspm --log-level=debug
ExecStop=/usr/bin/sh -c "/usr/bin/podman rm -f `cat /%t/%n-cid`"
KillMode=none
Type=forking
PIDFile=/%t/%n-pid

[Install]
WantedBy=multi-user.target
```

Thanks in advance.

**Comment by drenbutkovic** [comment]
Hi, 
log file is in attachment. 
Only one chain is active for test purpose. 
Chain no. 147 is configured to run_at every minute, cron * * * * *

[pg_timetable_debug_chain_147.txt](https://github.com/cybertec-postgresql/pg_timetable/files/10813395/pg_timetable_debug_chain_147.txt)

Tanks for fast response.

**Comment by pashagolub** [comment]
Would you please check patched version. The docker image is `cybertecpostgresql/pg_timetable:IS541`

Thanks in advance!

**Comment by drenbutkovic** [comment]
Hi,
after patch IS541, there are no more ERROR logs in table log.

![logs_after_patch](https://user-images.githubusercontent.com/41565252/220925562-cbc50126-8d3a-4900-a835-ed930ae7716f.png)

debug logs
[pg_timetable_IS541_debug_chain_147.txt](https://github.com/cybertec-postgresql/pg_timetable/files/10814086/pg_timetable_IS541_debug_chain_147.txt)

Thanks.

**Comment by pashagolub** [comment]
Nice! Thanks for your report!
