### ISSUE TITLE
disable database logging

### ISSUE THREAD

**Issue by nosovk** [cybertec-postgresql/pg_timetable#548]
**Is your feature request related to a problem? Please describe.**
We started migration from PG_CRON, and moved our jobs to PG_TIMETABLE. After migration, we found that database produces more ten 10GB of WAL in a day. 

**Describe the solution you'd like**
I would like to disable logging into PG database. It's good to fetch logs from std_out, but storing them in database is not ok.

**Describe alternatives you've considered**
```
ALTER TABLE timetable.log SET UNLOGGED; 
```

**Comment by pashagolub** [comment]
Hello. Thanks for your request. Sounds good!

Out of curiosity, what kind of workload can produce 10Gb logs? :-)

**Comment by nosovk** [comment]
We use Hasura as a backend for mobile application. And for some kinds of requests we do special cron-jobs, related to that action. And most of them are launched every second. Actually we have billing based on a cron. Every user that in a call or chat produces lots of cron jobs that added and deleted. And we store WAL for [WAL-G](https://github.com/wal-g/wal-g) backups.

**Comment by pashagolub** [comment]
Nice! It would be cool to know the results of your migration and maybe write a post about it.

Meanwhile, you can try a new option `--log-database-level=none` implemented in the assigned PR. Do you have an opportunity to build binaries from sources for tests?

**Comment by nosovk** [comment]
Unfortunately can't build for now, but I'm not in a hurry. Temporary solution also works.
