### ISSUE TITLE
--init exit code is always an error: 4 not 0

### ISSUE THREAD

**Issue by jamesmstone** [cybertec-postgresql/pg_timetable#556]
Hi! Thanks for your awesome work on pg_timetable.

I think there is a slight regression in the exit codes introduced in version 5.

**Describe the bug**

pg timetable no longer exits with a success (`0`) exit code when run with `--init`, since version **5**, even when it **is** still creating the schema.

This can cause a problem when scripting the initialisation of a database.

**To Reproduce**
Steps to reproduce the behaviour:

1. create a new db
2. run pgtimetable with `--init` flag
3. the exit code  for this is an error, however it does init the schema successfully.

```sh
#!/usr/bin/env bash

{
  for version in "3" "4.9" "5" "5.1"; do
    docker rm -f postgres || true
    docker run --rm --name postgres -ePOSTGRES_USER=scheduler -e POSTGRES_PASSWORD=mysecretpassword -d postgres
    timeout 90s /usr/bin/env bash -c "until docker exec postgres pg_isready ; do sleep 5 ; done" # wait for db to be ready

    docker run --rm \
      --link "postgres:postgres" \
      cybertecpostgresql/pg_timetable:$version \
      -h postgres -p 5432 -d postgres -u scheduler --password mysecretpassword -c worker001 --init

    echo "$? - exit code for pg_timetable: $version "
  done
} | grep "exit code for pg_timetable"

```

```text
0 - exit code for pg_timetable: 3 
0 - exit code for pg_timetable: 4.9 
4 - exit code for pg_timetable: 5 
4 - exit code for pg_timetable: 5.1 
```

**Comment by pashagolub** [comment]
Thanks a lot for reporting this bug James! Would you be so kind and confirm it's fixed by #557?

Thanks in advance!

**Comment by tourdownunder** [comment]
Seeing that the docker tag`latest` was published hours ago and adding it to the `version` for loop @jamesmstone provided I can confirm it now passes:

```text
0 - exit code for pg_timetable: latest 
```

**Comment by jamesmstone** [comment]
Thanks Pavlo for your quick fix, yes this fixes the issue. Thanks
