### ISSUE TITLE
Collect client messages for SQL tasks

### ISSUE THREAD

**Issue by a-mckinley** [cybertec-postgresql/pg_timetable#69]
For functions and stored procedures in SQL it would be great to capture client messages from ```raise notice``` etc with a configurable log level like ```set client_min_messages```.

I was hoping to migrate from airflow for scheduled SQL tasks but the inability to see stored proc logs means I can't at this point.

**Comment by pashagolub** [comment]
Sounds interesting. Can you, please, provide with task implementation and awaited output for it?

Thanks in advance!

**Comment by a-mckinley** [comment]
Hi @pashagolub apologies for the delay in responding.

I have a lot of long-running stored procs that run overnight that generate debug information (e.g. queries generated, and timings for different parts of the run) during execution.

This debug info is generated in statements like:

```sql
raise notice 'some info -%',some_variable;
raise debug 'some debug info -%',some_variable;
```

Currently I run these in Airflow pipelines and monitor the output for issues during development and deployment.

Being able to see capture and view client logs in a table (e.g. timetable.task_execution_output) would enable a complete replacement of Airflow and a pure in-Postgres solution which massively reduce the complexity of this type of solution.

**Comment by pashagolub** [comment]
Sorry for delay with answer. Welcome back from the winter vacations. :)

Thanks. I got your point. The only problem right now is standard `lib/pq` driver doesn't support notice processing.

I see two workarounds: 
- patch official driver and maintain our own version
- try to find another driver

How urgent and important is this issue for you?

**Comment by a-mckinley** [comment]
Hi @pashagolub.  I checked over at lib/pq and there was an open issue about this with a merge request [here](https://github.com/lib/pq/pull/794#issuecomment-573762886).

Hopefully it will be merged soon.

**Comment by pashagolub** [comment]
Oh great! so the plan is either of:
- rebase that patch against `lib/pq` master
- switch to `pgx`

Will see what happens earlier.

**Comment by a-mckinley** [comment]
Hi @pashagolub , FYI this feature has been merged in lib/pq in PR https://github.com/lib/pq/pull/932

**Comment by pashagolub** [comment]
@a-mckinley would you, please, test new `NOTICE` implementation in [69_notice_processing branch](/cybertec-postgresql/pg_timetable/tree/69_notice_processing)
