### ISSUE TITLE
Support interval scheduling

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pg_timetable#70]
It will allow to run job(s) below a minute, e.g. it is possible to schedule a `'10 seconds'::interval` task.

```
-- Schedule a job each 10 seconds
SELECT timetable.job_add (
    task_name => 'run every 10 seconds',
    task_function => $$INSERT INTO timetable.dummy_log (event_name) VALUES ('Cron test')$$,
    client_name => NULL, -- any worker may execute
    task_type => 'SQL',
    by_cron => '@interval(00:00:10)',
    by_minute => NULL,
    by_hour => NULL,
    by_day => NULL,
    by_month => NULL,
    by_day_of_week => NULL,
    max_instances => 1,
    live => TRUE,
    self_destruct => FALSE);
```

**Comment by a-mckinley** [comment]
This is a great feature.  I have a use case for this for generating state updates generated from GPS data, pushed to users where a sub minute resolution is needed.  

The @interval syntax seems to suit my usage perfectly.

**Comment by coding-kiko** [comment]
Is this currently working? Can you provide with a working example please? :)

**Comment by pashagolub** [comment]
Sure.
https://github.com/cybertec-postgresql/pg_timetable/blob/master/samples/Sleep.sql
https://pg-timetable.readthedocs.io/en/master/samples.html#run-tasks-in-autonomous-transaction

**Comment by coding-kiko** [comment]
Thank you, it worked! I was wondering if setting an interval of a task to run every 1 second makes affects the database performance noticeably. Is it something that you would recommend not doing?

**Comment by pashagolub** [comment]
You should measure that. :) But I would rather do more in one execution than execute several times

**Comment by coding-kiko** [comment]
Great, thanks for the reply. If I end up doing any kind of testing or benchmarking to measure it, I can send you the observations

**Comment by pashagolub** [comment]
That would be great!
