### ISSUE TITLE
Asynchronous chain execution

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pg_timetable#71]
Got an idea on async chains.
What if `pg_timetable` client will listen to his special channel. And when being notified by `NOTIFY name`, will execute chain configuration sent in the payload.

**Comment by a-mckinley** [comment]
As an extension to this idea, what about if you had special executors for notification payloads for different languages. 

E.g. create a base task with a python_notify type or something similar.
In the pg_timetable container, you could spawn a python process to execute the function specified at task creation time like.

```python
import some_cloud_service
def do_something(payload):
    some_cloud_service.push(payload['data'])
```

This idea could extend to lots of runtimes (e.g. Go/Python/Node etc.)  It could get around the limitations of not being able to run some server side languages in cloud managed Postgres (i.e. you can't run plpython on RDS).  Also, it would enable a simple architecture to execute async code in multiple languages based on postgres triggers/events.

The architecture I currently use is trigger->notify->rabbitmq->async_executor.  This requires multiple containers and a lot of boilerplate.  Executing directly in a pg_timetable executor means low boilerplate and consolidated system architecture.  You could even keep the function source code in the DB.

Please feel free to tell me this is a silly idea!

**Comment by pashagolub** [comment]
Why can't you use `SHELL` task, e.g. `python somescript.py`?

**Comment by a-mckinley** [comment]
That might work, with a self destructing task constructed as a string when calling timetable.job_add().  That would not actually need to utilise pg_notify() at all.

Just to clarify, will SHELL tasks run inside the pg_timetable container?

**Comment by pashagolub** [comment]
Sorry for a long delay, @a-mckinley. Was reviewing issues and have found your comment. :)

Yes, `SHELL` task run by `pg_timetable` inside the container\system `pg_timetable`'s binary is operating.
