### ISSUE TITLE
 how to send alert mail when job errors?

### ISSUE THREAD

**Issue by zard14** [cybertec-postgresql/pg_timetable#82]
Internal Task prebuilted SendMail function
I found out Table timestable.exection_log column returncode -1 means error

Should I setup another task to scan all error tasks and email? 
or setup any column in table timestable.chain_execution_config?

Could you help me how to setup this function? Thank you!

**Comment by pashagolub** [comment]
Hey. Thanks for cool question. We have a huge plans on supporting `events tasks`, e.g. `on_error`, `on_success`, so you can fire task if an error occurred.

Right now, you probably right, the only sane solution is to check logs and inform on your own. The other solution might be if you have Grafana monitoring, then you can set mail alerting inside it.

Yeah, sure. We can help you with your function. What exactly doesn't work on your side?

**Comment by zard14** [comment]
Thanks for your reply !

I will try Grafana monitoring to deal this problem first, and I'm looking forward the new features. :)
